name: hikari_client
description: Hikari remittance app client
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  package_info_plus: ^8.0.0
  remixicon: ^1.4.1
  flutter_markdown: ^0.6.18
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/profile.png
    - assets/images/banks/
    - assets/images/icons/
    - assets/policies/privacy_en.md
    - assets/policies/privacy_ja.md
    - assets/policies/privacy_ko.md
    - assets/policies/terms_en.md
    - assets/policies/terms_ja.md
    - assets/policies/terms_ko.md

flutter_native_splash:
  color: "#FFFFFF"                 # 라이트 배경
  image: assets/images/logo.png    # 네 로고 경로
  fullscreen: true
  android_12:
    color: "#FFFFFF"
    image: assets/images/logo.png
  # (선택) 다크모드 대응
  color_dark: "#0E1117"
  image_dark: assets/images/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF" # 배경 (혹은 투명 가능)
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios: true
